var options = {
  adsafe: false,
  bitwise: true,
  browser: false,
  cap: false,
  confusion: false,
  'continue': true,
  css: false,
  debug: false,
  devel: false,
  eqeq: false,
  es5: false,
  evil: true,
  forin: false,
  fragment: false,
  indent: 2,
  maxerr: 300,
  maxlen: 600,
  newcap: false,
  node: true,
  nomen: true,
  on: false,
  passfail: false,
  plusplus: false,
  predef: [
    // Mocha
    'describe', 'it', 'after', 'afterEach', 'before', 'beforeEach'
  ],
  regexp: true,
  rhino: false,
  safe: false,
  sloppy: true,
  sub: false,
  undef: false,
  unparam: false,
  vars: false,
  white: false,
  widget: false,
  windows: false
};

